### ISSUE TITLE
How to add example CRs

### ISSUE THREAD

**Issue by fekete-robert** [giantswarm/crd-docs-generator#115]
Hi, first of all, many thanks for this great tool!
I saw that the published docs include example CRs, but despite looking at the source codes in the different repos, I couldn't find out where they are coming from. How can you configure crd-docs-generator to include an example CR file for a CRD, or where does it look for the file by default?

**Comment by marians** [comment]
Hey @fekete-robert , sorry for the late reply. I have missed your question so far.

It is possible to include one example CR per CRD version. See an example here:

- [Published docs](https://docs.giantswarm.io/ui-api/management-api/crd/organizations.security.giantswarm.io/)
- [CRD](https://github.com/giantswarm/organization-operator/blob/v1.0.2/config/crd/security.giantswarm.io_organizations.yaml)
- [Example CR](https://github.com/giantswarm/organization-operator/blob/v1.0.2/docs/cr/security.giantswarm.io_v1alpha1_organization.yaml)

There is a configuration option `cr_path` which you can use to configure where to look up example CRs. See the [example config](https://github.com/giantswarm/crd-docs-generator/blob/main/config.example.yaml#L23).

The file names must also match a specific format `GROUP_VERSION_KIND.yaml`. See the Example CR linked above.

Does this answer your question?

**Comment by fekete-robert** [comment]
Thanks a lot for the help, I managed to get it work :)

**Comment by marians** [comment]
Good to hear. Closing the issue then.
